version: '2'
services:
  apache:
  #  image: 'php:7.1.0-apache'
   # image: 'tutum/apache-php'
    build:
      context: './apache'
      dockerfile: 'Dockerfile'
    container_name: 'apache'
    ports:
     - '80:80'
    links:
      - 'mysql:mysql.server.com'
      - 'mailhog:mail.server.com'
    volumes:
      - '/home/aston/Documents/docker-projects/html/:/var/www/html'
      - '/home/aston/Documents/docker-projects/apache/test.conf:/etc/apache2/sites-available/000-default.conf'
    restart: 'always'
    working_dir: '/var/www/html'

  mysql:
    image: 'mysql'
    container_name: 'mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'paris'
      MYSQL_DATABASE: 'library'
      MYSQL_USER: 'acme'
      MYSQL_PASSWORD: 'paris'
    volumes:
      - '/home/aston/Documents/docker-projects/mysql/:/root/'

  pma:
    image: 'phpmyadmin/phpmyadmin'
    container_name: 'pma'
    links:
      - 'mysql:mysql.server.com'
    ports:
      - '81:80'
    environment:
      PMA_HOST: 'mysql.server.com'

  mailhog:
      image: 'mailhog/mailhog'
      container_name: 'mailhog'
      ports:
        - '8002:8025'


#docker run -ti -p 80:80 -v /home/aston/Documents/docker-projects/www/html/:/var/www/html --name apache --rm php:7.1.0-apache bash